# Generated by Django 3.2.7 on 2022-06-17 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_account_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('startDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('endDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='edudegree',
            options={'ordering': ('startDate',)},
        ),
    ]
