# Generated by Django 3.2.7 on 2022-06-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20220618_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='account.Achievements'),
        ),
    ]
