# Generated by Django 3.2.7 on 2022-08-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_alter_talkfile_name'),
        ('account', '0020_account_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='generalmeetings',
            field=models.ManyToManyField(blank=True, to='meeting.Meeting'),
        ),
    ]
