# Generated by Django 3.2.7 on 2022-11-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20221022_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='dashboard_courses',
        ),
    ]
