# Generated by Django 3.2.7 on 2022-12-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_account_dashboard_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='dummy',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=10, null=True),
        ),
    ]
