# Generated by Django 3.2.7 on 2022-12-30 17:09

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_institute_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='instlogo',
            field=models.ImageField(blank=True, default=account.models.get_default_institute_logo, max_length=255, null=True, upload_to='images/'),
        ),
    ]
