# Generated by Django 3.2.7 on 2023-06-17 15:17

from django.db import migrations, models


def copy_username_to_phoneno(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        user.phoneno = user.username
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20230617_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phoneno',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),

    ## Custom operation to copy username to phoneno    
    migrations.RunPython(copy_username_to_phoneno),

    ]
