# Generated by Django 3.2.7 on 2023-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_account_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
