# Generated by Django 3.2.7 on 2023-08-04 11:29


from django.db import migrations, models


def copy_username_to_phoneno(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        user.phoneno = user.username
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_auto_20230719_1614'),
        ('account', '0036_alter_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='dashboard_courses_student',
        ),
        migrations.RemoveField(
            model_name='account',
            name='dashboard_courses_teacher',
        ),
        migrations.AddField(
            model_name='account',
            name='dashboard_courses',
            field=models.ManyToManyField(blank=True, related_name='dashboard_courses', to='course.Course'),
        ),

      ## Custom operation to copy username to phoneno    
      migrations.RunPython(copy_username_to_phoneno),


    ]
