# Generated by Django 3.2.7 on 2023-09-09 09:59

from django.db import migrations

def copy_username_to_phoneno(apps, schema_editor):
    User = apps.get_model('account', 'Account')
    for user in User.objects.all():
        user.phoneno = user.username
        user.save()



class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20230804_1129'),
    ]

    operations = [
     migrations.RunPython(copy_username_to_phoneno),       
    ]
