# Generated by Django 3.2.7 on 2024-04-29 13:50

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_aboutus_academicdetail_experience_licenseorcertificate_publication_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetail',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='academic_media/', validators=[account.models.validate_file_type]),
        ),
    ]
