# Generated by Django 3.2.7 on 2024-06-20 10:50

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_alter_academicdetail_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='delete_request_raised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_delete_request_raised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='licenseorcertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='licenseorcertificate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(default='Default About Us content'),
        ),
        migrations.AlterField(
            model_name='academicdetail',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='academic_media/', validators=[account.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ParentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, default='', max_length=50, verbose_name="Father's Name")),
                ('mother_name', models.CharField(blank=True, default='', max_length=50, verbose_name="Mother's Name")),
                ('father_phone', models.CharField(blank=True, default='', max_length=20, verbose_name="Father's Phone")),
                ('mother_phone', models.CharField(blank=True, default='', max_length=20, verbose_name="Mother's Phone")),
                ('father_email', models.EmailField(blank=True, default='', max_length=100, verbose_name="Father's Email")),
                ('mother_email', models.EmailField(blank=True, default='', max_length=100, verbose_name="Mother's Email")),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='', max_length=3)),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
