# Generated by Django 3.2.7 on 2022-04-11 19:55

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220410_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverImage', models.ImageField(blank=True, default=book.models.get_default_bookCoverImage, max_length=255, null=True, upload_to='images/')),
            ],
        ),
    ]
