# Generated by Django 3.2.7 on 2022-04-11 23:01

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_imageuploadtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='coverImage',
        ),
        migrations.AddField(
            model_name='book',
            name='coverimage',
            field=models.FileField(blank=True, default=book.models.get_default_bookCoverImage, max_length=255, null=True, upload_to='images/'),
        ),
    ]
