# Generated by Django 3.2.7 on 2022-04-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20220411_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadtest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
