# Generated by Django 3.2.7 on 2022-03-23 17:51

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CourseDesignedFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('boardofeducation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=99)),
            ],
        ),
        migrations.CreateModel(
            name='EducationBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('board', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.educationboard')),
                ('classname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.coursedesignedfor')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseShortName', models.CharField(max_length=50)),
                ('courseFullName', models.CharField(max_length=150)),
                ('courseGlobalCode', models.CharField(max_length=10)),
                ('courseLocalCode', models.CharField(max_length=10)),
                ('courseStatus', models.CharField(choices=[('closed', 'CLOSED'), ('ongoing', 'ONGOING')], default='ongoing', max_length=10)),
                ('courseStartDate', models.DateField(default=datetime.date.today)),
                ('courseEndDate', models.DateField(default=datetime.date.today)),
                ('educationboard', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('abouttheCourse', models.CharField(max_length=500)),
                ('instituteName', models.CharField(max_length=200)),
                ('instituteCity', models.CharField(max_length=100)),
                ('instituteCountry', models.CharField(max_length=100)),
                ('enrolledstudents', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default='0'), blank=True, default=list, null=True, size=99)),
                ('enrolementrequests', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default='0'), blank=True, default=list, null=True, size=99)),
                ('noticearray', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default='0'), blank=True, default=list, null=True, size=99)),
                ('classsection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.classsection')),
                ('designedFor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.coursedesignedfor')),
            ],
        ),
    ]
