# Generated by Django 3.2.7 on 2022-03-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('eclass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
          model_name='course',
          name='classes',
          field=models.ManyToManyField(to='eclass.Class'),
        ),
    ]
