# Generated by Django 3.2.7 on 2022-04-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('eclass', '0005_alter_class_options'),
        ('course', '0004_alter_course_classes'),
    ]

    operations = [
       # migrations.AlterField(
       #     model_name='course',
       #     name='classes',
       #     field=models.ManyToManyField(blank=True, to='eclass.Class'),
       # ),
    ]
