# Generated by Django 3.2.7 on 2022-04-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0007_auto_20220227_2212'),
        ('course', '0005_alter_course_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='noticeobjects',
            field=models.ManyToManyField(blank=True, to='noticeboard.NoticeBoard'),
        ),
    ]
