# Generated by Django 3.2.7 on 2022-10-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20221012_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrolementrequests',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrolledstudents',
        ),
    ]
