# Generated by Django 3.2.7 on 2022-10-17 01:05

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20221012_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='card_cover_image',
            field=models.ImageField(blank=True, default=course.models.get_default_card_cover_image, max_length=255, null=True, upload_to='images/'),
        ),
    ]
