# Generated by Django 3.2.7 on 2022-10-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_course_card_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursecredit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
