# Generated by Django 3.2.7 on 2022-10-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_coursecredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourseVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
