# Generated by Django 3.2.7 on 2022-10-20 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_allcoursevideos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllCourseVideos',
            new_name='VideoObject',
        ),
    ]
