# Generated by Django 3.2.7 on 2022-10-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_rename_allcoursevideos_videoobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='video_objects', to='course.VideoObject'),
        ),
    ]
