# Generated by Django 3.2.7 on 2022-10-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_course_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoobject',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videoobject',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='videoobject',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
