# Generated by Django 3.2.7 on 2022-10-21 20:59

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20221020_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('creationDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('creationTime', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ('creationDate',),
            },
        ),
        migrations.AlterModelOptions(
            name='videoobject',
            options={'ordering': ('creationDate',)},
        ),
        migrations.AddField(
            model_name='videoobject',
            name='creationDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='videoobject',
            name='creationTime',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
