# Generated by Django 3.2.7 on 2022-10-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('course', '0018_course_courselinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='course_assignments', to='assignment.Assignment'),
        ),
    ]
