# Generated by Django 3.2.7 on 2022-10-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_rename_post_ticket'),
        ('course', '0019_course_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='course_tickets', to='tickets.Ticket'),
        ),
    ]
