# Generated by Django 3.2.7 on 2022-10-24 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_allcategoriesofcourse'),
        ('course', '0020_course_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ticketCategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_cat_course', to='tickets.allcategoriesofcourse'),
        ),
    ]
