# Generated by Django 3.2.7 on 2022-10-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_zone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
