# Generated by Django 3.2.7 on 2022-11-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_delete_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseShortName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
