# Generated by Django 3.2.7 on 2022-11-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_auto_20221115_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileobject',
            name='link',
        ),
    ]
