# Generated by Django 3.2.7 on 2023-07-19 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0029_alter_course_aboutthecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_creater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='allcourse_teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
