# Generated by Django 3.2.7 on 2023-08-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0030_auto_20230719_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
