# Generated by Django 3.2.7 on 2023-09-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0001_initial'),
        ('course', '0031_remove_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='classes', to='eclass.Class'),
        ),
    ]
