# Generated by Django 3.2.7 on 2024-06-20 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0033_course_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='course_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
