# Generated by Django 3.2.7 on 2024-08-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0015_alter_institutefee_options'),
        ('course', '0034_auto_20240620_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='linked_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_courses', to='institute.batch'),
        ),
        migrations.AddField(
            model_name='course',
            name='linked_institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_courses', to='institute.institute'),
        ),
    ]
