# Generated by Django 3.2.7 on 2022-01-21 13:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('groupusers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='ChatComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttext', models.TextField()),
                ('commenttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatcommenter', to=settings.AUTH_USER_MODEL)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatcomment', to='chat.chatgroup')),
            ],
            options={
                'ordering': ('commenttime',),
            },
        ),
    ]
