# Generated by Django 3.2.7 on 2022-08-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatgroup_groupusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='groupType',
            field=models.CharField(blank=True, choices=[('oneoone', 'ONEOONE'), ('group', 'GROUP')], default='group', max_length=10, null=True),
        ),
    ]
