# Generated by Django 3.2.7 on 2022-08-22 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatgroup_grouptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='lastmsgTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
