# Generated by Django 3.2.7 on 2022-08-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatgroup_lastmsgtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='chatcomments',
            field=models.ManyToManyField(blank=True, to='chat.ChatComment'),
        ),
    ]
