# Generated by Django 3.2.7 on 2022-08-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatgroup_chatcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcomment',
            name='title',
            field=models.CharField(default='chatcomment', max_length=100),
        ),
    ]
