# Generated by Django 3.2.7 on 2023-07-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatgroup_groupuserobjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='lastMsg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
