# Generated by Django 3.2.7 on 2022-05-24 06:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting', '0002_meeting_creater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talkfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('talkfile', models.FileField(blank=True, max_length=255, null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='timezone',
            field=models.CharField(choices=[('ist', 'IST'), ('cet', 'CET'), ('usct', 'usCT')], default='scheduled', max_length=10),
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talktitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('talkdate', models.DateField(default=datetime.date.today)),
                ('talktime', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('outspeaker', models.CharField(blank=True, max_length=200, null=True)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_talk', to=settings.AUTH_USER_MODEL)),
                ('talkfiles', models.ManyToManyField(blank=True, to='meeting.Talkfile')),
            ],
        ),
    ]
