# Generated by Django 3.2.7 on 2022-05-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20220524_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
