# Generated by Django 3.2.7 on 2022-05-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_meeting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='classStatus',
            field=models.CharField(choices=[('scheduled', 'SCHEDULED'), ('ongoing', 'ONGOING'), ('cancelled', 'CANCELLED'), ('postponed', 'POSTPONED'), ('over', 'OVER')], default='scheduled', max_length=10),
        ),
    ]
