# Generated by Django 3.2.7 on 2022-05-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_alter_meeting_classstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
