# Generated by Django 3.2.7 on 2022-05-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_meeting_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='contributions',
            field=models.ManyToManyField(blank=True, to='meeting.Presentation'),
        ),
    ]
