# Generated by Django 3.2.7 on 2022-05-30 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_meeting_contributions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkObjs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='presentation',
            name='talkdate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
