# Generated by Django 3.2.7 on 2022-05-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_auto_20220530_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkfile',
            name='name',
            field=models.CharField(blank=True, default='Namenotgiven', max_length=500, null=True),
        ),
    ]
