# Generated by Django 3.2.7 on 2022-12-27 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_alter_talkfile_talkfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
