# Generated by Django 3.2.7 on 2023-11-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0016_meeting_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meetingStatus',
            field=models.CharField(choices=[('scheduled', 'SCHEDULED'), ('ongoing', 'ONGOING'), ('cancelled', 'CANCELLED'), ('postponed', 'POSTPONED'), ('completed', 'COMPLETED')], default='scheduled', max_length=10),
        ),
    ]
