# Generated by Django 3.2.7 on 2022-10-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountAPIs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='users',
            new_name='chatgroup',
        ),
    ]
