# Generated by Django 3.2.7 on 2022-04-12 04:25

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_imageuploadtest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadtest',
            name='coverimage',
            field=models.ImageField(blank=True, default=book.models.get_default_bookCoverImage, max_length=255, null=True, upload_to='images/'),
        ),
    ]
