# Generated by Django 3.2.7 on 2022-02-22 22:35

import account.models
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('firstname', models.CharField(blank=True, default='', max_length=20, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, default='', max_length=20, verbose_name='lastname')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=account.models.get_default_profile_image, max_length=255, null=True, upload_to='images/')),
                ('hide_email', models.BooleanField(default=True)),
                ('registrationid', models.CharField(default='', max_length=60, verbose_name='regid')),
                ('gender', models.CharField(blank=True, default='', max_length=20, verbose_name='gender')),
                ('position', models.CharField(blank=True, default='', max_length=20, verbose_name='position')),
                ('dateofbirth', models.DateField(default=datetime.date.today, max_length=8, verbose_name='dob')),
                ('dashboardcourses', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default='0'), blank=True, default=list, null=True, size=99)),
                ('enrolledcourses', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default='0'), blank=True, default=list, null=True, size=99)),
                ('enrolledrequestcourses', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default='0'), blank=True, default=list, null=True, size=99)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('usertitle', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.usertitle')),
                ('usertype', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.usertype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
