# Generated by Django 3.2.7 on 2022-02-26 21:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_usertitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='noticeIds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default='0'), blank=True, default=list, null=True, size=99),
        ),
    ]
