# Generated by Django 3.2.7 on 2022-04-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_noticeobjects'),
        ('account', '0004_account_noticeids'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dashboard_courses',
            field=models.ManyToManyField(blank=True, to='course.Course'),
        ),
    ]
