# Generated by Django 3.2.7 on 2022-05-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_certificate_degreename_documentcopy_edudegree_institute_marksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='educationDegrees',
            field=models.ManyToManyField(blank=True, to='account.EduDegree'),
        ),
    ]
