# Generated by Django 3.2.7 on 2022-05-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_account_educationdegrees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edudegree',
            name='certificates',
            field=models.ManyToManyField(blank=True, default=None, to='account.Certificate'),
        ),
        migrations.AlterField(
            model_name='edudegree',
            name='marksheets',
            field=models.ManyToManyField(blank=True, default=None, to='account.MarkSheet'),
        ),
    ]
