# Generated by Django 3.2.7 on 2022-05-18 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20220518_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edudegree',
            name='endDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='edudegree',
            name='startDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
