# Generated by Django 3.2.7 on 2022-06-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20220617_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careof', models.CharField(blank=True, max_length=200, null=True)),
                ('houseno', models.CharField(blank=True, max_length=100, null=True)),
                ('streetno', models.CharField(blank=True, max_length=200, null=True)),
                ('placename', models.CharField(blank=True, max_length=200, null=True)),
                ('postoffice', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('policestn', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('addressType', models.CharField(blank=True, choices=[('present', 'PRESENT'), ('permanent', 'PERMANENT')], default='present', max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='account.Address'),
        ),
    ]
