# Generated by Django 3.2.7 on 2022-08-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20220816_2215'),
        ('account', '0021_account_generalmeetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='generalchatgroups',
            field=models.ManyToManyField(blank=True, to='chat.ChatGroup'),
        ),
    ]
