# Generated by Django 3.2.7 on 2022-09-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0008_alter_noticeboard_options'),
        ('account', '0023_remove_account_noticeids'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='removednoticeids',
            field=models.ManyToManyField(blank=True, related_name='noticeids_removed', to='noticeboard.NoticeBoard'),
        ),
        migrations.AlterField(
            model_name='account',
            name='noticeids',
            field=models.ManyToManyField(blank=True, related_name='noticeids_read', to='noticeboard.NoticeBoard'),
        ),
    ]
