# Generated by Django 3.2.7 on 2022-09-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20220526_1838'),
        ('account', '0025_auto_20220905_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='dashboardcourses',
        ),
        migrations.RemoveField(
            model_name='account',
            name='enrolledcourses',
        ),
        migrations.RemoveField(
            model_name='account',
            name='enrolledrequestcourses',
        ),
        migrations.AddField(
            model_name='account',
            name='dashboard_courses_student',
            field=models.ManyToManyField(blank=True, related_name='dashboard_courses_student', to='course.Course'),
        ),
        migrations.AddField(
            model_name='account',
            name='dashboard_courses_teacher',
            field=models.ManyToManyField(blank=True, related_name='dashboard_courses_teacher', to='course.Course'),
        ),
        migrations.AddField(
            model_name='account',
            name='enrolled_courses_student',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses_student', to='course.Course'),
        ),
        migrations.AddField(
            model_name='account',
            name='enrollrequest_courses_student',
            field=models.ManyToManyField(blank=True, related_name='enroll_request_courses_student', to='course.Course'),
        ),
        migrations.AddField(
            model_name='account',
            name='enrollrequest_courses_teacher',
            field=models.ManyToManyField(blank=True, related_name='enroll_request_courses_teacher', to='course.Course'),
        ),
    ]
