# Generated by Django 3.2.7 on 2022-10-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20220913_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dobCert_doc',
            field=models.FileField(blank=True, max_length=1055, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='govtId1_doc',
            field=models.FileField(blank=True, max_length=1055, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='govtId2_doc',
            field=models.FileField(blank=True, max_length=1055, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='officeId_doc',
            field=models.FileField(blank=True, max_length=1055, null=True, upload_to='images/'),
        ),
    ]
