# Generated by Django 3.2.7 on 2023-06-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default=None, max_length=100, null=True, unique=True, verbose_name='email'),
        ),
    ]
