# Generated by Django 3.2.7 on 2022-10-22 19:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('afile', models.FileField(blank=True, max_length=1055, null=True, upload_to='images/')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('publishDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('dueDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('credit', models.CharField(blank=True, max_length=100, null=True)),
                ('answerFiles', models.ManyToManyField(blank=True, related_name='attachment_answer', to='assignment.AssignmentAttachment')),
                ('creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creater_assignment', to=settings.AUTH_USER_MODEL)),
                ('questionFiles', models.ManyToManyField(blank=True, related_name='attachment_questions', to='assignment.AssignmentAttachment')),
            ],
            options={
                'ordering': ('dueDate',),
            },
        ),
    ]
