name: Django CI
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: myproject
          POSTGRES_USER: myprojectuser
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django psycopg2-binary
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found. Installing only Django and psycopg2-binary."
        fi
    - name: List directory contents
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -R
    - name: Run migrations
      env:
        DJANGO_SETTINGS_MODULE: myproject.settings
      run: |
        # Change to the directory containing manage.py
        cd myproject
        python manage.py migrate
    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: myproject.settings
      run: |
        # Change to the directory containing manage.py
        cd myproject
        python manage.py test
    - name: Run linting
      run: |
        pip install flake8
        # Run flake8 from the root directory
        flake8 . --exclude=.git,__pycache__,migrations
