name: Django CI
on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: myproject
          POSTGRES_USER: myprojectuser
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Debug repository structure
      run: |
        echo "Current directory after checkout:"
        pwd
        echo "List all files and directories:"
        ls -R

    - name: Run migrations
      env:
        DJANGO_SETTINGS_MODULE: myproject.settings
      run: |
        cd $GITHUB_WORKSPACE/DashoTest
        python manage.py migrate
    
    - name: Run tests
      env:
        DJANGO_SETTINGS_MODULE: myproject.settings
      run: |
        cd $GITHUB_WORKSPACE/DashoTest
        python manage.py test
    
    - name: Run linting
      run: |
        pip install flake8
        flake8 . --exclude=.git,__pycache__,migrations
